home:
  title: "IB1" # title on the main page
  description: "An imageboard that doesn't require Javascript." # description on the main page
  language: "en" # html lang attribute
web:
  domain: "localhost" # domain name, required for cookies
  listener: "localhost:8080" # address and port to listen on
database:
  type: "sqlite" # supported : sqlite, mysql
  url: "ib1.db" # connection string or sqlite database path
captcha:
  enabled: true # enable captcha
boards: # list of boards
  - enabled: true
    name: "b"
    title: "random"
    description: "Random stuff"
  - enabled: true
    name: "a"
    title: "fun zone"
    description: "Second board"
  - enabled: true
    name: "x"
    title: "paranormal"
    description: "Schizo central"
