home:
  title: "IB1" # title on the main page
  description: "An imageboard that does not require Javascript." # description on the main page
  language: "en" # html lang attribute
web:
  domain: "localhost" # domain name, required for cookies
  listener: "localhost:8080" # address and port to listen on
media:
  directory: "./media" # media directory
  thumbnail: "./thumbnail" # thumbnails directory
database:
  type: "sqlite" # supported : sqlite, mysql
  url: "ib1.db" # connection string or sqlite database path
captcha:
  enabled: true # enable captcha
  length: 7 # number of characters in the captcha
board:
  maxThreads: 40 # maximum of threads active in the catalog
boards: # list of boards
  - enabled: true
    name: "b"
    title: "random"
    description: "Random stuff"
  - enabled: true
    name: "a"
    title: "fun zone"
    description: "Second board"
  - enabled: true
    name: "x"
    title: "paranormal"
    description: "Schizo central"
