// Code generated by "stringer -type=Privilege"; DO NOT EDIT.

package db

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NONE-0]
	_ = x[CREATE_BOARD-1]
	_ = x[ADMINISTRATION-2]
	_ = x[MANAGE_USER-3]
	_ = x[BAN_USER-4]
	_ = x[APPROVE_MEDIA-5]
	_ = x[BAN_MEDIA-6]
	_ = x[REMOVE_MEDIA-7]
	_ = x[REMOVE_POST-8]
	_ = x[HIDE_POST-9]
	_ = x[BYPASS_CAPTCHA-10]
	_ = x[BYPASS_MEDIA_APPROVAL-11]
	_ = x[VIEW_HIDDEN-12]
	_ = x[VIEW_PENDING_MEDIA-13]
	_ = x[LAST-14]
}

const _Privilege_name = "NONECREATE_BOARDADMINISTRATIONMANAGE_USERBAN_USERAPPROVE_MEDIABAN_MEDIAREMOVE_MEDIAREMOVE_POSTHIDE_POSTBYPASS_CAPTCHABYPASS_MEDIA_APPROVALVIEW_HIDDENVIEW_PENDING_MEDIALAST"

var _Privilege_index = [...]uint8{0, 4, 16, 30, 41, 49, 62, 71, 83, 94, 103, 117, 138, 149, 167, 171}

func (i Privilege) String() string {
	if i < 0 || i >= Privilege(len(_Privilege_index)-1) {
		return "Privilege(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Privilege_name[_Privilege_index[i]:_Privilege_index[i+1]]
}
